version: "3.9"

services:
  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - labmate-internal
  api:
    image: frankwhite/labmate-api:latest
    environment:
      - MONGO_URL=mongodb://db:27017/labmate
      - PORT=8000
    ports:
      - "8585:8000"
    networks:
      - labmate-internal
    depends_on:
      - db
  app:
    image: frankwhite/labmate:latest
    environment:
      - API_HOSTNAME=localhost
      - API_PORT=8585
    ports:
      - "8998:8080"
    depends_on:
      - api

volumes:
  mongodb_data:

networks:
  labmate-internal: