version: "3.9"

services:
  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
  api:
    build: packages/server
    environment:
      - MONGO_URL=mongodb://db:27017/labmate
      - PORT=8000
    ports:
      - "8585:8000"
    depends_on:
      - db
  app:
    build: packages/client
    environment:
      - API_HOSTNAME=localhost
      - API_PORT=8585
    ports:
      - "8998:8080"
    depends_on:
      - api

volumes:
  mongodb_data: