version: "3.9"

services:
  db:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - labmate-internal
  api:
    build: packages/server
    ports:
      - "8585:8000"
    networks:
      - labmate-internal
  app:
    build: packages/client
    environment:
      - API_HOSTNAME=localhost
      - API_PORT=8585
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  mongodb_data:

networks:
  labmate-internal: